apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/carbide-digit-439821-n3/locations/us-central1-c/clusters/cluste-1

